[package]
name = "jockey-semantic"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
jockey-ast = { path = "../ast" }
jockey-ir = { path = "../ir" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
jockey-lexer = { path = "../lexer" }
jockey-parser = { path = "../parser" }