[package]
name = "jocky-semantic"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
jocky-ast = { path = "../ast" }
jocky-ir = { path = "../ir" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
jocky-lexer = { path = "../lexer" }
jocky-parser = { path = "../parser" }