[package]
name = "jocky-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "jocky"
path = "src/main.rs"

[dependencies]
jocky-lexer = { path = "../lexer" }
jocky-parser = { path = "../parser" }
jocky-ast = { path = "../ast" }
jocky-semantic = { path = "../semantic" }
jocky-ir = { path = "../ir" }
jocky-hir = { path = "../hir" }
jocky-mir = { path = "../mir" }
jocky-backend = { path = "../backend" }
jocky-runtime = { path = "../../runtime" }
jocky-runtime-capabilities = { path = "../../runtime/capabilities" }
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
whoami = "1.6.1"
ureq = { version = "2.10", features = ["json"] }

[features]
default = []
llvm = ["jocky-backend/llvm"]

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
