//! Generated by jockey Compiler v0.1.0
//! Investigation: process_triage
//! Target: Linux-X64
//! Required capabilities: ["PROCESS_READ", "SYSTEM_INFO_READ", "FILE_HASH"]

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use jockey_runtime::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut evidence = EvidenceCollector::new("process_triage");
    evidence.collect_system_info();
    evidence.collect_processes(vec!["pid", "name", "parent", "command_line", "start_time"]);
    evidence.set_output_format("json", "processes.json");

    evidence.finalize()?;
    println!("Evidence collection complete");
    Ok(())
}
