//! Generated by jocky Compiler v0.1.0
//! Investigation: process_triage
//! Target: Linux-X64
//! Required capabilities: ["SYSTEM_INFO_READ", "PROCESS_READ", "NETWORK_READ", "FILE_HASH"]

#![allow(unused_imports, unused_variables)]
use jocky_runtime::*;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut evidence = EvidenceCollector::new("process_triage");
    evidence.collect_system_info()?;
    evidence.collect_processes(vec!["pid".to_string(), "name".to_string(), "parent".to_string(), "command_line".to_string(), "start_time".to_string()])?;
    evidence.collect_network_connections()?;
    evidence.set_output_format("json", "process_triage_evidence.json");

    evidence.finalize()?;
    println!("Evidence collection complete");
    Ok(())
}
