//! Full Native End-to-End Pipeline & Semantic Behavioral Tests
//!
//! Tests the complete compiler lifecycle:
//! `.tfg` DSL source
//!   ↓
//! Lexer → Parser → Semantic Analysis → HIR → MIR → Programmatic LLVM → Native Executable
//!   ↓
//! Execute in controlled environment
//!   ↓
//! Forensic evidence collected & exported
//!   ↓
//! SHA-256 + Merkle inclusion integrity verified
//!   ↓
//! Tamper detection tested

use std::fs;
use std::process::Command;

use traceforge_backend::llvm::LlvmBackend;
use traceforge_ir::BuildConfig;
use traceforge_runtime_evidence::{verify_evidence_deep, VerificationStatus};

#[test]
fn test_native_end_to_end_forensic_pipeline() {
    let source = r#"
investigation "native_semantic_triage" {
    collect system_info
    collect processes
    collect network_connections
    collect files "/etc" { recursive: false }
    collect timeline
    export evidence "native_evidence.json"
}
"#;

    let temp_dir =
        std::env::temp_dir().join(format!("traceforge_native_test_{}", std::process::id()));
    let _ = fs::remove_dir_all(&temp_dir);
    fs::create_dir_all(&temp_dir).expect("Failed to create temp test directory");

    // 1. Lexer
    let mut lexer = traceforge_lexer::Lexer::new(source);
    let tokens = lexer.tokenize().expect("Lexer failed");

    // 2. Parser
    let mut parser = traceforge_parser::Parser::new(tokens);
    let ast = parser.parse().expect("Parser failed");

    // 3. Semantic Analysis
    let mut analyzer = traceforge_semantic::SemanticAnalyzer::new();
    let ir = analyzer.analyze(&ast).expect("Semantic analysis failed");

    // 4. HIR Lowering
    let hir = traceforge_hir::HirLowering::lower(&ast, &ir.required_capabilities, source)
        .expect("HIR lowering failed");

    // 5. MIR Lowering
    let mir = traceforge_mir::MirLowering::lower(&hir).expect("MIR lowering failed");

    // 6. Programmatic LLVM Compilation to Native Executable
    let config = BuildConfig::default();
    let backend = LlvmBackend::new(config);
    let metadata = backend
        .compile(&mir, &temp_dir)
        .expect("Native compilation via LLVM and Clang failed");

    assert_eq!(metadata.investigation_name, "native_semantic_triage");
    assert!(!metadata.artifact_hash.is_empty());

    let binary_name = "native_semantic_triage-linux-x64".to_string();
    let binary_path = temp_dir.join(&binary_name);
    assert!(
        binary_path.exists(),
        "Native ELF binary was not produced at {:?}",
        binary_path
    );

    // 7. Execute Native Binary in Temp Directory
    let exec_output = Command::new(&binary_path)
        .current_dir(&temp_dir)
        .output()
        .expect("Failed to execute native forensic binary");

    assert!(
        exec_output.status.success(),
        "Native binary execution failed: stderr: {}",
        String::from_utf8_lossy(&exec_output.stderr)
    );

    // 8. Assert Evidence File Output
    let evidence_path = temp_dir.join("native_evidence.json");
    assert!(
        evidence_path.exists(),
        "native_evidence.json was not generated by binary"
    );

    let evidence_raw =
        fs::read_to_string(&evidence_path).expect("Failed to read generated evidence");
    let evidence_json: serde_json::Value =
        serde_json::from_str(&evidence_raw).expect("Evidence must be valid JSON");

    // 9. Semantic Behavioral Verification
    let records = evidence_json
        .as_array()
        .expect("Evidence must be a JSON array of records");
    assert!(
        !records.is_empty(),
        "Evidence records array must not be empty"
    );

    // Check system_info evidence record
    let has_system_info = records.iter().any(|r| {
        r.get("source").and_then(|s| s.as_str()) == Some("system_info")
            || r.get("hostname").is_some()
            || r.get("os").is_some()
            || r.get("event_type").and_then(|t| t.as_str()) == Some("system_info")
    });
    assert!(
        has_system_info,
        "Semantic check: Evidence must contain real system_info telemetry"
    );

    // Check processes evidence record
    let has_processes = records.iter().any(|r| {
        r.get("source").and_then(|s| s.as_str()) == Some("processes")
            || r.get("process_name").is_some()
            || r.get("pid").is_some()
            || r.get("name").is_some()
    });
    assert!(
        has_processes,
        "Semantic check: Evidence must contain real process telemetry"
    );

    // Check network evidence record
    let has_network = records.iter().any(|r| {
        r.get("source").and_then(|s| s.as_str()) == Some("network")
            || r.get("connections").is_some()
            || r.get("local_address").is_some()
            || r.get("protocol").is_some()
            || r.get("family").is_some()
    });
    assert!(
        has_network,
        "Semantic check: Evidence must contain real network telemetry"
    );

    // Check files evidence record
    let has_files = records.iter().any(|r| {
        r.get("source").and_then(|s| s.as_str()) == Some("files")
            || r.get("path").is_some()
            || r.get("file_path").is_some()
    });
    assert!(
        has_files,
        "Semantic check: Evidence must contain real filesystem telemetry"
    );

    // 10. Deep Cryptographic Verification
    let meta_path = temp_dir.join("native_evidence.json.meta.json");
    assert!(
        meta_path.exists(),
        "Sidecar metadata file must be created alongside evidence"
    );

    let deep_result =
        verify_evidence_deep(evidence_path.to_str().unwrap(), meta_path.to_str().unwrap())
            .expect("Deep verification failed");

    assert_eq!(
        deep_result.base_result.status,
        VerificationStatus::Verified,
        "Fresh evidence must have Verified status"
    );
    assert!(
        deep_result.per_item_proofs_valid,
        "Fresh evidence must pass per-item Merkle proof validation"
    );
    assert_eq!(
        deep_result.failed_items.len(),
        0,
        "No records should be failed in fresh evidence"
    );
    assert!(
        deep_result.verified_items > 0,
        "At least one record verified against Merkle tree"
    );

    // 11. Tamper Detection Test
    // Modify one character in evidence file to simulate evidence tampering
    let mut tampered_json = evidence_json.clone();
    if let Some(first_record) = tampered_json.as_array_mut().and_then(|r| r.get_mut(0)) {
        if let Some(obj) = first_record.as_object_mut() {
            obj.insert(
                "tampered_field".to_string(),
                serde_json::json!("unauthorized_tampering"),
            );
        }
    }
    let tampered_path = temp_dir.join("tampered_evidence.json");
    fs::write(
        &tampered_path,
        serde_json::to_string_pretty(&tampered_json).unwrap(),
    )
    .unwrap();

    let tampered_verify_res =
        verify_evidence_deep(tampered_path.to_str().unwrap(), meta_path.to_str().unwrap()).expect(
            "Deep verification on tampered evidence should run and return detection result",
        );

    assert!(
        tampered_verify_res.base_result.status != VerificationStatus::Verified
            || !tampered_verify_res.per_item_proofs_valid
            || !tampered_verify_res.failed_items.is_empty(),
        "Tampered evidence must fail verification"
    );

    // Cleanup
    let _ = fs::remove_dir_all(&temp_dir);
}
