[package]
name = "jocky-runtime-security"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
serde = { workspace = true }
serde_json = "1.0"
chrono = { workspace = true }
sha2 = { workspace = true }
jocky-runtime-network = { path = "../network" }
