[package]
name = "traceforge-compiler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
traceforge-lexer = { path = "lexer" }
traceforge-parser = { path = "parser" }
traceforge-ast = { path = "ast" }
traceforge-semantic = { path = "semantic" }
traceforge-ir = { path = "ir" }
traceforge-backend = { path = "backend" }
traceforge-cli = { path = "cli" }
anyhow = { workspace = true }
tracing = { workspace = true }