[package]
name = "jockey-compiler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
jockey-lexer = { path = "lexer" }
jockey-parser = { path = "parser" }
jockey-ast = { path = "ast" }
jockey-semantic = { path = "semantic" }
jockey-ir = { path = "ir" }
jockey-hir = { path = "hir" }
jockey-mir = { path = "mir" }
jockey-backend = { path = "backend" }
jockey-cli = { path = "cli" }
anyhow = { workspace = true }
tracing = { workspace = true }