[package]
name = "jocky-compiler"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }

[dependencies]
jocky-lexer = { path = "lexer" }
jocky-parser = { path = "parser" }
jocky-ast = { path = "ast" }
jocky-semantic = { path = "semantic" }
jocky-ir = { path = "ir" }
jocky-hir = { path = "hir" }
jocky-mir = { path = "mir" }
jocky-backend = { path = "backend" }
jocky-cli = { path = "cli" }
anyhow = { workspace = true }
tracing = { workspace = true }