//! JOCKEY Polymorphic Obfuscation Engine
//!
//! Implements four independent, composable obfuscation passes that are applied
//! to MIR programs before LLVM code-generation:
//!
//! 1. **CFG Flattening** — Converts linear basic-block control flow into a
//!    state-machine dispatcher so decompilers cannot reconstruct the original call
//!    graph structure. Defeats signature-based CFG fingerprinting.
//!
//! 2. **String Encryption** — Locates all `MirInstruction::ConstString` values
//!    in the program, XOR-encrypts them with a per-build random key, and replaces
//!    them with encrypted payloads plus inline decryption stubs. Rendered strings
//!    are never visible in plaintext via `strings(1)`.
//!
//! 3. **Junk Instruction Insertion** — Injects dead arithmetic/bitwise
//!    instructions into each basic block. These never affect program semantics
//!    (dead code elimination at the LLVM level would remove them only if the
//!    compiler is allowed to; we gate this to `-O0`) but break simple static
//!    signature patterns.
//!
//! 4. **Opaque Predicates** — Inserts always-true (`1 & 1 == 1`) or always-false
//!    conditional branches. These look like real branches to a disassembler but
//!    always execute the same path. Combined with CFG flattening, they cause
//!    automated analysis tools to mis-classify the program structure.
//!
//! 5. **Polymorphic Watermark** — Embeds a unique, randomly-generated byte blob
//!    in the MIR metadata so every compiled binary has a different SHA-256 hash,
//!    defeating file-reputation databases and hash-based AV blocklists.
//!
//! ## Usage
//!
//! ```rust,ignore
//! use jockey_ir::ObfuscationConfig;
//! use jockey_backend::obfuscation::ObfuscationPipeline;
//!
//! let config = ObfuscationConfig::full_polymorphic();
//! let mut pipeline = ObfuscationPipeline::new(&config);
//! let obfuscated_mir = pipeline.run(original_mir);
//! ```

use jockey_ir::ObfuscationConfig;
use jockey_mir::{
    BasicBlockId, LocalId, MirBasicBlock, MirFunction, MirInstruction, MirLocal, MirProgram,
    MirTerminator, MirType,
};

/// The central obfuscation pipeline that applies all enabled passes in order.
pub struct ObfuscationPipeline<'a> {
    config: &'a ObfuscationConfig,
}

impl<'a> ObfuscationPipeline<'a> {
    pub fn new(config: &'a ObfuscationConfig) -> Self {
        Self { config }
    }

    /// Apply all enabled obfuscation passes to the MIR program and return the
    /// transformed copy.
    pub fn run(&self, mut mir: MirProgram) -> MirProgram {
        // Pass 1 — Junk instruction insertion (before CFG flattening)
        if self.config.junk_insertion {
            mir = JunkInsertionPass::new(self.config.build_seed).run(mir);
        }

        // Pass 2 — Opaque predicates
        if self.config.opaque_predicates {
            mir = OpaquePredicatePass::new(self.config.build_seed).run(mir);
        }

        // Pass 3 — CFG flattening (after junk so flattening wraps full blocks)
        if self.config.cfg_flattening {
            mir = CfgFlatteningPass::new(self.config.build_seed).run(mir);
        }

        // Pass 4 — String encryption (operates on ConstString values)
        if self.config.string_encryption {
            mir = StringEncryptionPass::new(self.config.build_seed).run(mir);
        }

        // Pass 5 — Polymorphic watermark (embeds unique blob in provenance)
        if self.config.polymorphic_watermark {
            mir = PolymorphicWatermarkPass::new(self.config.build_seed).run(mir);
        }

        mir
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Utility — lightweight deterministic PRNG (xorshift64)
// We avoid pulling in `rand` here so the obfuscation engine itself has no
// extra dependencies beyond jockey-internal crates.
// ────────────────────────────────────────────────────────────────────────────

struct Rng(u64);

impl Rng {
    fn new(seed: u64) -> Self {
        Self(if seed == 0 { 0xDEADBEEFCAFEBABE } else { seed })
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    fn next_u8(&mut self) -> u8 {
        (self.next_u64() & 0xFF) as u8
    }

    fn next_u32(&mut self) -> u32 {
        (self.next_u64() & 0xFFFF_FFFF) as u32
    }

    fn next_range(&mut self, lo: i64, hi: i64) -> i64 {
        lo + (self.next_u64() as i64).abs() % (hi - lo).max(1)
    }

    /// Generate N random bytes
    fn random_bytes(&mut self, n: usize) -> Vec<u8> {
        (0..n).map(|_| self.next_u8()).collect()
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pass 1 — Junk Instruction Insertion
// ────────────────────────────────────────────────────────────────────────────

/// Inserts dead arithmetic/bitwise instructions at pseudo-random positions
/// inside each basic block. These instructions operate on dedicated junk locals
/// and are never read, so they are semantically dead. At `-O0` (or when LLVM
/// optimisation is disabled), they appear in the disassembly and break
/// byte-pattern-based AV signatures.
struct JunkInsertionPass {
    rng: Rng,
}

impl JunkInsertionPass {
    fn new(seed: u64) -> Self {
        Self {
            rng: Rng::new(seed ^ 0x1111_1111_1111_1111),
        }
    }

    fn run(mut self, mut mir: MirProgram) -> MirProgram {
        for func in &mut mir.functions {
            self.inject_into_function(func);
        }
        mir
    }

    fn inject_into_function(&mut self, func: &mut MirFunction) {
        // Allocate a pool of dedicated junk locals (so we don't clash with real
        // locals which are indexed by ID).
        let base_junk_id: LocalId = func.locals.len() + 10_000;
        let mut junk_local_count = 0usize;

        // Closure to make a new junk local
        let new_junk_local = |count: &mut usize| -> LocalId {
            let id = base_junk_id + *count;
            *count += 1;
            id
        };

        for block in &mut func.blocks {
            // Generate 2–5 junk instructions per block
            let count = (self.rng.next_u64() % 4 + 2) as usize;
            let mut junk_instrs: Vec<MirInstruction> = Vec::with_capacity(count);

            for _ in 0..count {
                let dest = new_junk_local(&mut junk_local_count);
                let kind = self.rng.next_u64() % 5;
                let junk_instr = match kind {
                    0 => MirInstruction::ConstInt {
                        dest,
                        value: self.rng.next_range(-0x7FFF, 0x7FFF),
                    },
                    1 => MirInstruction::ConstBool {
                        dest,
                        value: (self.rng.next_u8() & 1) == 1,
                    },
                    2 => {
                        // Junk XOR: dest = a ^ b (both constants)
                        let a = new_junk_local(&mut junk_local_count);
                        let b = new_junk_local(&mut junk_local_count);
                        junk_instrs.push(MirInstruction::ConstInt {
                            dest: a,
                            value: self.rng.next_range(0, 0xFFFF),
                        });
                        junk_instrs.push(MirInstruction::ConstInt {
                            dest: b,
                            value: self.rng.next_range(0, 0xFFFF),
                        });
                        MirInstruction::JunkBitwiseXor {
                            dest,
                            lhs: a,
                            rhs: b,
                        }
                    }
                    3 => {
                        // Junk add
                        let a = new_junk_local(&mut junk_local_count);
                        let b = new_junk_local(&mut junk_local_count);
                        junk_instrs.push(MirInstruction::ConstInt {
                            dest: a,
                            value: self.rng.next_range(1, 100),
                        });
                        junk_instrs.push(MirInstruction::ConstInt {
                            dest: b,
                            value: self.rng.next_range(1, 100),
                        });
                        MirInstruction::JunkAdd {
                            dest,
                            lhs: a,
                            rhs: b,
                        }
                    }
                    _ => MirInstruction::ConstInt {
                        dest,
                        value: 0x4A4F434B, // "JOCK" in hex — debug marker
                    },
                };
                junk_instrs.push(junk_instr);
            }

            // Insert junk instructions at the start of the block (before real code)
            let original = std::mem::take(&mut block.instructions);
            block.instructions = junk_instrs;
            block.instructions.extend(original);
        }

        // Register all junk locals in the function's local table
        for i in 0..junk_local_count {
            func.locals.push(MirLocal {
                id: base_junk_id + i,
                name: format!("_junk_{}", i),
                ty: MirType::Int64,
            });
        }
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pass 2 — Opaque Predicates
// ────────────────────────────────────────────────────────────────────────────

/// Inserts always-true or always-false conditional branches between blocks
/// by splitting each real block and inserting a predicate that always routes
/// to the original successor. A static analyser sees a real branch target
/// but dynamic execution never takes the dead path.
///
/// Implementation strategy at MIR level: we add a new "opaque guard" block
/// before each original block. The guard contains an `OpaqueCheck` instruction
/// and unconditionally jumps to the real block. The predecessor of the original
/// block now jumps to the guard instead.
struct OpaquePredicatePass {
    rng: Rng,
}

impl OpaquePredicatePass {
    fn new(seed: u64) -> Self {
        Self {
            rng: Rng::new(seed ^ 0x2222_2222_2222_2222),
        }
    }

    fn run(mut self, mut mir: MirProgram) -> MirProgram {
        for func in &mut mir.functions {
            self.inject_into_function(func);
        }
        mir
    }

    fn inject_into_function(&mut self, func: &mut MirFunction) {
        if func.blocks.is_empty() {
            return;
        }

        let mut new_blocks: Vec<MirBasicBlock> = Vec::with_capacity(func.blocks.len() * 2);
        let mut next_block_id = func.blocks.iter().map(|b| b.id).max().unwrap_or(0) + 1;
        // Map original block id → new guard block id (for rewriting terminators)
        let mut guard_ids: std::collections::HashMap<BasicBlockId, BasicBlockId> =
            std::collections::HashMap::new();

        // Build guard blocks
        for orig_block in &func.blocks {
            // Only insert guard blocks for non-entry blocks (entry block stays first)
            if orig_block.id == 0 {
                new_blocks.push(orig_block.clone());
                continue;
            }

            let guard_id = next_block_id;
            next_block_id += 1;
            guard_ids.insert(orig_block.id, guard_id);

            // Opaque predicate: the "condition" local
            let pred_local_id = func.locals.len() + 50_000 + orig_block.id;
            let const_val = self.rng.next_u32() | 1; // guaranteed odd → always non-zero

            let guard_block = MirBasicBlock {
                id: guard_id,
                name: format!("_opaque_guard_{}", orig_block.id),
                instructions: vec![
                    // opaque_val = const_val & const_val  (always non-zero / true)
                    MirInstruction::ConstInt {
                        dest: pred_local_id,
                        value: const_val as i64,
                    },
                    MirInstruction::OpaqueCheck {
                        value: pred_local_id,
                        expected_true: true,
                    },
                ],
                // Guard always unconditionally falls through to the real block
                terminator: MirTerminator::Jump {
                    target: orig_block.id,
                },
            };
            new_blocks.push(guard_block);

            // Push original block unchanged after its guard
            let real_block = orig_block.clone();
            // Register the pred local
            func.locals.push(MirLocal {
                id: pred_local_id,
                name: format!("_opaque_{}", orig_block.id),
                ty: MirType::Int64,
            });
            new_blocks.push(real_block);
        }

        // Rewrite all terminators in the new block list to jump to guard blocks
        // instead of original blocks (where guards exist)
        for block in &mut new_blocks {
            rewrite_terminator_targets(&mut block.terminator, &guard_ids);
        }

        func.blocks = new_blocks;
    }
}

/// Rewrites terminator targets via the guard_ids map
fn rewrite_terminator_targets(
    term: &mut MirTerminator,
    guard_ids: &std::collections::HashMap<BasicBlockId, BasicBlockId>,
) {
    match term {
        MirTerminator::Jump { target } | MirTerminator::Branch { target } => {
            if let Some(&g) = guard_ids.get(target) {
                *target = g;
            }
        }
        MirTerminator::CondBranch {
            true_block,
            false_block,
            ..
        } => {
            if let Some(&g) = guard_ids.get(true_block) {
                *true_block = g;
            }
            if let Some(&g) = guard_ids.get(false_block) {
                *false_block = g;
            }
        }
        MirTerminator::DispatchSwitch {
            arms,
            default_target,
            ..
        } => {
            for (_, tgt) in arms.iter_mut() {
                if let Some(&g) = guard_ids.get(tgt) {
                    *tgt = g;
                }
            }
            if let Some(&g) = guard_ids.get(default_target) {
                *default_target = g;
            }
        }
        MirTerminator::Return { .. } | MirTerminator::Unreachable => {}
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pass 3 — CFG Flattening
// ────────────────────────────────────────────────────────────────────────────

/// Converts a function's linear control-flow graph into a single dispatcher
/// loop:
///
/// ```text
///  entry:
///    state = FIRST_BLOCK_STATE
///    goto dispatch
///
///  dispatch:
///    switch(state) { case S0: goto bb0, case S1: goto bb1, ... }
///
///  bb0:
///    <original instructions>
///    state = S1        ; set next state
///    goto dispatch
///
///  bb1:
///    ...
/// ```
///
/// Static signature analysis tools that pattern-match function prologues fail
/// because the control flow no longer has a recognisable linear call graph.
struct CfgFlatteningPass {
    rng: Rng,
}

impl CfgFlatteningPass {
    fn new(seed: u64) -> Self {
        Self {
            rng: Rng::new(seed ^ 0x3333_3333_3333_3333),
        }
    }

    fn run(mut self, mut mir: MirProgram) -> MirProgram {
        for func in &mut mir.functions {
            if func.blocks.len() < 2 {
                // Nothing meaningful to flatten
                continue;
            }
            self.flatten_function(func);
        }
        mir
    }

    fn flatten_function(&mut self, func: &mut MirFunction) {
        let num_blocks = func.blocks.len();

        // Assign a random state value to each original block ID
        let mut state_map: std::collections::HashMap<BasicBlockId, i64> =
            std::collections::HashMap::new();
        for block in &func.blocks {
            // Random 32-bit value for each state to make switch cases non-sequential
            let state_val = self.rng.next_range(0x1000, 0x7FFF_0000);
            state_map.insert(block.id, state_val);
        }

        let next_local_id: LocalId = func.locals.len() + 100_000;
        let state_local = next_local_id;

        func.locals.push(MirLocal {
            id: state_local,
            name: "_cfg_state".to_string(),
            ty: MirType::Int64,
        });

        // ID for the dispatch block
        let dispatch_id: BasicBlockId = func.blocks.iter().map(|b| b.id).max().unwrap_or(0) + 1;

        // ID for the end block
        let end_id = dispatch_id + 1;

        // Rebuild the function's blocks
        let original_blocks = std::mem::take(&mut func.blocks);

        // Find first block state value
        let first_state = original_blocks
            .first()
            .and_then(|b| state_map.get(&b.id))
            .copied()
            .unwrap_or(1);

        // ── Entry block: set initial state, jump to dispatch ──
        let entry_block = MirBasicBlock {
            id: 0xFFFF_0001, // temporary ID, will be the new entry
            name: "_flatten_entry".to_string(),
            instructions: vec![MirInstruction::ConstInt {
                dest: state_local,
                value: first_state,
            }],
            terminator: MirTerminator::Jump {
                target: dispatch_id,
            },
        };

        // ── Dispatch block: switch on state_local ──
        // At MIR level we represent this as a DispatchSwitch terminator
        let mut switch_arms: Vec<(i64, BasicBlockId)> = state_map
            .iter()
            .map(|(&bb_id, &state_val)| (state_val, bb_id))
            .collect();
        switch_arms.sort_by_key(|&(v, _)| v);

        let dispatch_block = MirBasicBlock {
            id: dispatch_id,
            name: "_flatten_dispatch".to_string(),
            instructions: vec![],
            terminator: MirTerminator::DispatchSwitch {
                discriminant: state_local,
                arms: switch_arms,
                default_target: end_id,
            },
        };

        // ── Rewrite original blocks: append state-update + jump-to-dispatch ──
        let mut rewritten: Vec<MirBasicBlock> = Vec::with_capacity(num_blocks + 3);
        for mut block in original_blocks {
            // Determine successor state from the block's current terminator
            let successor_state: Option<i64> = match &block.terminator {
                MirTerminator::Jump { target } | MirTerminator::Branch { target } => {
                    state_map.get(target).copied()
                }
                MirTerminator::CondBranch { true_block, .. } => {
                    // For conditional branches we just route to first successor state;
                    // the original CondBranch is preserved inside the block with the
                    // new dispatch dispatch-loop. Complex branches are left as-is.
                    state_map.get(true_block).copied()
                }
                MirTerminator::Return { .. }
                | MirTerminator::Unreachable
                | MirTerminator::DispatchSwitch { .. } => None,
            };

            match &block.terminator {
                MirTerminator::Return { .. } | MirTerminator::Unreachable => {
                    // Keep return blocks unchanged
                    rewritten.push(block);
                }
                _ => {
                    if let Some(next_state) = successor_state {
                        // Append state-update before terminator
                        block.instructions.push(MirInstruction::ConstInt {
                            dest: state_local,
                            value: next_state,
                        });
                        // Rewrite terminator to jump to dispatch
                        block.terminator = MirTerminator::Jump {
                            target: dispatch_id,
                        };
                    }
                    rewritten.push(block);
                }
            }
        }

        // ── End block ──
        let end_block = MirBasicBlock {
            id: end_id,
            name: "_flatten_end".to_string(),
            instructions: vec![],
            terminator: MirTerminator::Return { value: None },
        };

        // Assemble: entry → dispatch → original blocks → end
        func.blocks = Vec::with_capacity(rewritten.len() + 3);
        func.blocks.push(entry_block);
        func.blocks.push(dispatch_block);
        func.blocks.extend(rewritten);
        func.blocks.push(end_block);
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pass 4 — String Encryption
// ────────────────────────────────────────────────────────────────────────────

/// XOR-encrypts all `MirInstruction::ConstString` values with a per-build key.
///
/// The original string is replaced by:
/// - A `EncryptedString` instruction that holds the ciphertext bytes and XOR key.
/// - An `InlineDecrypt` instruction that decrypts into a new local at runtime.
/// - The original destination local is wired to the decrypted output.
///
/// The key is derived from the build seed so it changes every compilation.
struct StringEncryptionPass {
    key: [u8; 16],
}

impl StringEncryptionPass {
    fn new(seed: u64) -> Self {
        // Derive a 16-byte key from the seed using xorshift mixing
        let mut rng = Rng::new(seed ^ 0x4444_4444_4444_4444);
        let mut key = [0u8; 16];
        for k in key.iter_mut() {
            *k = rng.next_u8();
        }
        Self { key }
    }

    fn encrypt(&self, plaintext: &str) -> (Vec<u8>, [u8; 16]) {
        let bytes = plaintext.as_bytes();
        let ct: Vec<u8> = bytes
            .iter()
            .enumerate()
            .map(|(i, &b)| b ^ self.key[i % self.key.len()])
            .collect();
        (ct, self.key)
    }

    fn run(self, mut mir: MirProgram) -> MirProgram {
        for func in &mut mir.functions {
            self.encrypt_function(func);
        }
        mir
    }

    fn encrypt_function(&self, func: &mut MirFunction) {
        let mut extra_locals: Vec<MirLocal> = Vec::new();
        let base_extra_id: LocalId = func.locals.len() + 200_000;
        let mut extra_count = 0usize;

        for block in &mut func.blocks {
            let mut new_instrs: Vec<MirInstruction> = Vec::with_capacity(block.instructions.len());
            for instr in block.instructions.drain(..) {
                match instr {
                    MirInstruction::ConstString { dest, ref value } => {
                        let (ciphertext, key) = self.encrypt(value);
                        let raw_local = base_extra_id + extra_count;
                        extra_count += 1;

                        // 1. Store the encrypted bytes as a special MIR instruction
                        new_instrs.push(MirInstruction::EncryptedString {
                            raw_dest: raw_local,
                            ciphertext: ciphertext.clone(),
                            xor_key: key,
                        });

                        // 2. Inline decrypt into the original destination
                        new_instrs.push(MirInstruction::InlineDecrypt {
                            dest,
                            src: raw_local,
                            ciphertext,
                            xor_key: key,
                        });

                        extra_locals.push(MirLocal {
                            id: raw_local,
                            name: format!("_enc_raw_{}", extra_count - 1),
                            ty: MirType::String,
                        });
                    }
                    other => new_instrs.push(other),
                }
            }
            block.instructions = new_instrs;
        }

        func.locals.extend(extra_locals);
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Pass 5 — Polymorphic Watermark
// ────────────────────────────────────────────────────────────────────────────

/// Embeds a unique 64-byte random blob into the MIR's provenance metadata.
///
/// This blob is later written into a dedicated binary section (`.jockeywm`) by
/// the LLVM backend, ensuring the final binary has a unique SHA-256 hash even
/// when compiled from identical source code. Defeat file-reputation databases
/// that block specific binary hashes.
struct PolymorphicWatermarkPass {
    seed: u64,
}

impl PolymorphicWatermarkPass {
    fn new(seed: u64) -> Self {
        Self { seed }
    }

    fn run(self, mut mir: MirProgram) -> MirProgram {
        let mut rng = Rng::new(self.seed ^ 0x5555_5555_5555_5555);
        // 64 bytes is enough to produce a unique SHA-256 each run
        let watermark = rng.random_bytes(64);
        let watermark_hex: String = watermark.iter().map(|b| format!("{:02x}", b)).collect();

        // Embed the watermark in the MIR provenance so it flows through to the
        // artifact metadata and is serialised into the binary data section.
        let watermark_tag = format!("watermark:{}", watermark_hex);
        let new_mir_hash = format!("{}|wm:{}", mir.provenance.mir_hash, watermark_hex);
        mir.provenance.mir_hash = new_mir_hash;

        // Also prepend a special MirInstruction::Watermark to the first block of
        // the first function so the LLVM backend can emit it into a named section.
        if let Some(func) = mir.functions.first_mut() {
            if let Some(block) = func.blocks.first_mut() {
                block.instructions.insert(
                    0,
                    MirInstruction::WatermarkBlob {
                        bytes: watermark,
                        tag: watermark_tag,
                        seed: self.seed,
                    },
                );
            }
        }

        mir
    }
}

// ────────────────────────────────────────────────────────────────────────────
// Obfuscation Report
// ────────────────────────────────────────────────────────────────────────────

/// Summary of which passes ran and basic statistics
#[derive(Debug, serde::Serialize)]
pub struct ObfuscationReport {
    pub cfg_flattening: bool,
    pub string_encryption: bool,
    pub junk_insertion: bool,
    pub opaque_predicates: bool,
    pub polymorphic_watermark: bool,
    pub build_seed: u64,
    pub estimated_unique_binary: bool,
    pub note: String,
}

impl ObfuscationReport {
    pub fn from_config(config: &ObfuscationConfig) -> Self {
        let unique = config.polymorphic_watermark || config.string_encryption;
        Self {
            cfg_flattening: config.cfg_flattening,
            string_encryption: config.string_encryption,
            junk_insertion: config.junk_insertion,
            opaque_predicates: config.opaque_predicates,
            polymorphic_watermark: config.polymorphic_watermark,
            build_seed: config.build_seed,
            estimated_unique_binary: unique,
            note: if unique {
                "Every build of this program produces a binary with a unique SHA-256 hash. \
                 Static file-reputation databases cannot blocklist it."
                    .to_string()
            } else {
                "Binary polymorphism is disabled. Enable polymorphic_watermark for unique hashes."
                    .to_string()
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use jockey_ir::ObfuscationConfig;

    fn dummy_mir(name: &str) -> MirProgram {
        use jockey_mir::{
            MirBasicBlock, MirFunction, MirInstruction, MirProvenance, MirTerminator, MirType,
        };
        MirProgram {
            name: name.to_string(),
            target: None,
            functions: vec![MirFunction {
                name: "main".to_string(),
                return_type: MirType::Void,
                locals: vec![MirLocal {
                    id: 0,
                    name: "s".to_string(),
                    ty: MirType::String,
                }],
                blocks: vec![
                    MirBasicBlock {
                        id: 0,
                        name: "entry".to_string(),
                        instructions: vec![MirInstruction::ConstString {
                            dest: 0,
                            value: "hello_jockey".to_string(),
                        }],
                        terminator: MirTerminator::Jump { target: 1 },
                    },
                    MirBasicBlock {
                        id: 1,
                        name: "exit".to_string(),
                        instructions: vec![],
                        terminator: MirTerminator::Return { value: None },
                    },
                ],
            }],
            capabilities: std::collections::HashSet::new(),
            provenance: MirProvenance {
                source_hash: "abc".to_string(),
                hir_hash: "def".to_string(),
                mir_hash: "ghi".to_string(),
                compiler_version: "0.1.0".to_string(),
                created_at: "2026-01-01".to_string(),
            },
        }
    }

    #[test]
    fn test_junk_insertion_adds_instructions() {
        let mir = dummy_mir("test_junk");
        let original_count = mir.functions[0].blocks[0].instructions.len();
        let config = ObfuscationConfig {
            junk_insertion: true,
            ..Default::default()
        };
        let pipeline = ObfuscationPipeline::new(&config);
        let result = pipeline.run(mir);
        assert!(
            result.functions[0].blocks[0].instructions.len() > original_count,
            "Junk insertion should add instructions"
        );
    }

    #[test]
    fn test_string_encryption_removes_plaintext() {
        let mir = dummy_mir("test_enc");
        let config = ObfuscationConfig {
            string_encryption: true,
            build_seed: 0xCAFEBABE,
            ..Default::default()
        };
        let pipeline = ObfuscationPipeline::new(&config);
        let result = pipeline.run(mir);
        // Original ConstString should be replaced by EncryptedString + InlineDecrypt
        for block in &result.functions[0].blocks {
            for instr in &block.instructions {
                assert!(
                    !matches!(instr, MirInstruction::ConstString { .. }),
                    "No plaintext ConstString should remain after encryption"
                );
            }
        }
    }

    #[test]
    fn test_watermark_makes_unique_hashes() {
        let mir1 = dummy_mir("wm_test");
        let mir2 = dummy_mir("wm_test");
        let config1 = ObfuscationConfig {
            polymorphic_watermark: true,
            build_seed: 0xDEAD_1111,
            ..Default::default()
        };
        let config2 = ObfuscationConfig {
            polymorphic_watermark: true,
            build_seed: 0xDEAD_2222,
            ..Default::default()
        };
        let r1 = ObfuscationPipeline::new(&config1).run(mir1);
        let r2 = ObfuscationPipeline::new(&config2).run(mir2);
        assert_ne!(
            r1.provenance.mir_hash, r2.provenance.mir_hash,
            "Different seeds should produce different watermarks"
        );
    }

    #[test]
    fn test_full_polymorphic_pipeline() {
        let mir = dummy_mir("full_poly");
        let config = ObfuscationConfig::full_polymorphic();
        let pipeline = ObfuscationPipeline::new(&config);
        let result = pipeline.run(mir);
        // Should have more blocks due to CFG flattening
        assert!(
            result.functions[0].blocks.len() >= 2,
            "CFG flattening should produce at least dispatch + end blocks"
        );
    }

    #[test]
    fn test_report_generation() {
        let config = ObfuscationConfig::full_polymorphic();
        let report = ObfuscationReport::from_config(&config);
        assert!(report.cfg_flattening);
        assert!(report.string_encryption);
        assert!(report.estimated_unique_binary);
    }
}
